name: Build and deploy Node.js app to Azure Web App - umsehdhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Copy server files to dist
        run: |
          echo "Copying server.js to dist folder..."
          cp server.js dist/
          
          echo "Creating production package.json..."
          cat > dist/package.json << 'EOF'
          {
            "name": "sehd-admissions-dashboard",
            "version": "1.0.0",
            "scripts": {
              "start": "node server.js"
            },
            "dependencies": {
              "express": "^4.18.2"
            },
            "engines": {
              "node": "22.x"
            }
          }
          EOF
          
          echo "Contents of dist folder:"
          ls -la dist/
          
          echo "Verifying server.js exists:"
          cat dist/server.js | head -5

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'umsehdhub'
          slot-name: 'Production'
          package: './dist'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B88EB2A821454ABFAC101AFF29BB0E36 }}