# GitHub Actions workflow to build and deploy a Vite React app to Azure Web App

name: Build and deploy Vite app to Azure Web App - umsehdhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

- name: Install dependencies and build Vite app
  working-directory: sehd-admissions-dashboard
  run: |
    npm install
    npm run build
    cp public/web.config dist/
    cp package.json dist/
    cd dist
    npm install --production

      - name: Confirm build output exists
        run: ls -R sehd-admissions-dashboard/dist

      - name: Zip the build output (dist/)
        run: |
          cd sehd-admissions-dashboard
          zip -r ../release.zip dist/ server.js package.json

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'umsehdhub'  # Replace with your Azure Web App name
          package: ./sehd-admissions-dashboard
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
